import modules.classe_arbre as ca
a = ca.Arbre('A')
a.Sag = ca.Arbre('B') 
a.Sag.Sag = ca.Arbre('C') 
a.Sag.Sag.Sag = ca.Arbre('D')
a.Sag.Sag.Sad = ca.Arbre('E') 
a.Sad = ca.Arbre('F')
a.Sad.Sag = ca.Arbre('G')
a.Sad.Sad = ca.Arbre('H')
a.Sad.Sad.Sad = ca.Arbre('I')
a.RepresentationArbre("")
dico_hauteur= a.Hauteur(a)
print(f"Dictionnaires des hauteurs des noeuds : {dico_hauteur}")
taille_arbre = a.Taille(a)
print(f"Taille de l'arbre : {taille_arbre}")
lste_feuille = a.LstFeuilles(a)
print(f"Liste des feuilles : {lste_feuille}")
lste_noeuds_internes = a.LstNoeudsInternes(a,lste_feuille)
print(f"Liste des noeuds internes : {lste_noeuds_internes}")   
hauteur_arbre = a.HauteurArbre(dico_hauteur,lste_feuille)
print(f"Hauteur de l'arbre : {hauteur_arbre}")
lcb = a.LC(dico_hauteur)
print(f"Longueur de cheminement : {lcb}")
lce = a.LCE(dico_hauteur,lste_feuille)
print(f"Longueur de cheminement externe : {lce}")
lci = a.LCI(dico_hauteur,lste_noeuds_internes)
print(f"Longueur de cheminement interne : {lci}")
pm = a.PM(lcb,a)
print(f"Profondeur moyenne  : {pm}")
pme = a.PME(lce,lste_feuille)
print(f"Profondeur moyenne externe  : {pme}")
pmi = a.PMI(lci,lste_feuille,a)
print(f"Profondeur moyenne interne : {pmi}")


